import React from 'react'
import { createTheme, ThemeProvider, styled } from '@mui/material/styles';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

declare module '@mui/material/styles' {
  interface Theme {
    status: {
      danger: string
    },
  }
  // allow configuration using `createTheme`
  interface ThemeOptions {
    status?: {
      danger?: string
    },
  }
}



const theme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#3808b1',
    },
    secondary: {
      main: '#ba60cd',
    },
  }
})

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <ThemeProvider theme={theme}>
      {children}
    </ThemeProvider>
  )
}
